name: "Validate tweet action"
description: "Validate a tweet using twitter's validation library"

inputs:
  tweet:
    description: "The tweet to validate"
    required: true

runs:
  using: "composite"
  steps:
    - run: npm install --no-save twitter-text
      shell: bash
    - uses: actions/github-script@v4
      env:
        TWEET: ${{ inputs.tweet }}
      with:
        script: |
          const twitter = require("twitter-text");
          const script = require('${{ github.action_path }}/main.js');
          await script({github, context, core, twitter});
